- name: configuring mongdb repo 
  ansible.builtin.copy:
   src: mongodb.repo
   dest: /etc/yum.repos.d/mongodb.repo

- name: Installing mongodb
  ansible.builtin.package:
   name: mongodb-org
   state: present

- name: Updating the mongodb config to public
  ansible.builtin.replace:
   path: /etc/mongod.conf
   regexp: '127.0.0.1'
   replace: '0.0.0.0'

- name: starting mongodb
  ansible.builtin.systemd:
   name: mongod
   state: restarted
   enabled: true

