- name: configuring mongdb repo 
  ansible.builtin.copy:
   src: mongodb.repo
   dest: /etc/yum.repos.d/mongodb.repo

- name: Installing mongodb
  ansible.builtin.package:
   name: mongodb-org
   state: present

- name: Updating the mongodb config to public
  ansible.builtin.replace:
   path: /etc/mongod.conf
   regexp: '127.0.0.1'
   replace: '0.0.0.0'

- name: starting mongodb
  ansible.builtin.systemd:
   name: mongod
   state: restarted
   enabled: true

- name: downloading and extracting the mongodb schema
  ansible.builtin.unarchive:
   src: https://github.com/stans-robot-project/{{COMPONENT}}/archive/main.zip
   dest: /tmp
   remote_src: yes

- name: injecting mongodb catalogue schema
  community.mongodb.mongodb_shell:
   file: "/tmp/{{COMPONENT}}-main/{{item}}.js"
   idempotent: yes
  loop:
     - catalogue
     - users

# - name: injecting mongodb user schema
#   community.mongodb.mongodb_shell:
#    file: "/tmp/{{COMPONENT}}-main/users.js"
#    idempotent: yes

