- name: Play1
  hosts: all
  vars:
      URL: play.google.com
  tasks:
    - name: This is variable demo
      ansible.builtin.debug:
       msg: The value of variable is {{ URL }}

  tasks:
   - name: This is local variable demo
      ansible.builtin.debug:
       msg: The value of variable is {{ URL }}
      vars:
        URL: task.google.com

