- name: Demo on variables
  hosts: all
  vars:
      URL: play.google.com
      CARNAME: Ford
  vars_prompt:
   - name: URLName
     prompt: enter the prompt variable
     private: no
  vars_files:
   - dev-vars.yml
  tasks:
    - name: This is variable demo
      ansible.builtin.debug:
       msg: The value of variable is {{ URL }}

    - name: This is local variable demo
      ansible.builtin.debug:
        msg: "{{ URL }}"
      vars:
        URL: task.google.com

    - name: This is commandline variable demo
      ansible.builtin.debug:
        msg: The value of car is {{ CARNAME }}
      
    - name: The prompt variable demo
      ansible.builtin.debug:
        msg: The prompt variable is {{ URLName }}

