- name: Shell Module with register
  hosts: all
  tasks:
    - name: Demo on shell Module
      ansible.builtin.shell: uptime
      register: OUT

    - name: Demo on printing register value
      ansible.builtin.debug:
       msg: "{{ OUT.stdout }}"

    - name: Decalaring variable
      set_fact:
        STATUS: "{{ OUT.rc }}"

    - name: uptime command exit commandline
      ansible.builtin.debug:
       msg: The exit code of uptime command is {{ STATUS }}