- name: Demo on condition
  hosts: all
  vars:
   action: false
  # gather_facts: false
  tasks: 
    - name: Run this task if it only centos
      ansible.builtin.debug:
       msg: I am centos Machine
      when: ansible_distribution == "CentOS"

    - name: Run this task if it only debian
      ansible.builtin.debug:
       msg:  I am debian Machine
      when: ansible_distribution == "debian"
    
    - name: Run this action
      ansible.builtin.debug:
        msg: I am learing ansible and only print if action is true 
      when: action

   - name: Run only when bar is undefined
      ansible.builtin.debug:
        msg: BAR is not decalared 
      when: bar is undefined