- name: Demo on tags
  hosts: all
  tasks:
   - name: This is frontend task
     ansible.builtin.debug:
      msg: Installing frontend
     tags: frontend

   - name: Starting frontend
     ansible.builtin.debug:
      msg: Starting frontend
     tags: frontend 

   - name: This is user task
     ansible.builtin.debug:
      msg: Installing user
     tags: user

   - name: Starting user
     ansible.builtin.debug:
      msg: Starting user
     tags: user
    
   - name: This is cart task
     ansible.builtin.debug:
      msg: Installing cart
     tags: cart

   - name: Starting cart
     ansible.builtin.debug:
      msg: Starting cart
     tags: cart
