- name: Demonstarting privilge escalation
  hosts: all
  become: yes
  tasks:
    - name: checking user id
      ansible.builtin.shell: id
      register: OUT

    - name: Demo on printing register value
      ansible.builtin.debug:
       msg: "{{ OUT.stdout }}"